# Generated by Django 2.1.2 on 2020-03-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equinixgroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=100)),
                ('transpondername', models.CharField(max_length=100)),
                ('transponderip', models.CharField(max_length=100)),
                ('transponderusername', models.CharField(max_length=100)),
                ('transponderpassword', models.CharField(max_length=100)),
                ('opsname', models.CharField(max_length=100)),
                ('opsip', models.CharField(max_length=100)),
                ('opsusername', models.CharField(max_length=100)),
                ('opspassword', models.CharField(max_length=100)),
                ('interfacename', models.CharField(max_length=100)),
            ],
        ),
    ]
