# Generated by Django 2.1.2 on 2020-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equinixgroups',
            name='id',
        ),
        migrations.AlterField(
            model_name='equinixgroups',
            name='groupname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
